name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:
jobs:
  golangci:
    strategy:
      matrix:
        go: [1.13, 1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
