name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        go: [1.13, 1.19]
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
  test:
    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - go: 1.13
            os: ubuntu-latest
    name: test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: build
        run: go build
      - name: test
        run: go test ./... -v
